# PyTorch Basics
- tensors like numpy
- tensors on the *gpu*

## Package imports

In [1]:
import torch
# import torch.nn as nn
# import torch.nn.functional as F
# import torch.optim as optim
# import torchvision

In [2]:
# from pprint import pprint

import matplotlib.pyplot as plt
import numpy as np

#from IPython.core.debugger import set_trace

# Tensors
tensors - our building blocks

## Tensors in numpy and pytorch

In [3]:
from numpy.linalg import inv
from numpy.linalg import multi_dot as mdot

In [4]:
# numpy
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# torch
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [6]:
# numpy
X = np.random.random((5, 3))
X

array([[0.29766008, 0.88908442, 0.19784801],
       [0.86616119, 0.48625976, 0.33754372],
       [0.35633964, 0.41473864, 0.90670672],
       [0.80977643, 0.1109464 , 0.86010471],
       [0.61741869, 0.0081563 , 0.21985396]])

In [7]:
# pytorch
Y = torch.rand((5, 3))
Y

tensor([[0.8246, 0.0699, 0.3145],
        [0.5546, 0.1727, 0.9096],
        [0.4394, 0.4614, 0.2207],
        [0.2626, 0.4189, 0.7983],
        [0.8012, 0.6591, 0.1031]])

In [8]:
X.shape

(5, 3)

In [9]:
Y.shape

torch.Size([5, 3])

In [10]:
# numpy
X.T @ X

array([[2.00275836, 0.92848972, 1.50658873],
       [0.92848972, 1.21130343, 0.81330254],
       [1.50658873, 0.81330254, 1.76331255]])

In [11]:
# torch
Y.t() @ Y

tensor([[1.8915, 0.9942, 1.1530],
        [0.9942, 0.8574, 0.6832],
        [1.1530, 0.6832, 1.6228]])

In [12]:
# numpy
inv(X.T @ X)

array([[ 1.53785071, -0.42961818, -1.11579708],
       [-0.42961818,  1.31593501, -0.23988678],
       [-1.11579708, -0.23988678,  1.63110495]])

In [13]:
# torch
torch.inverse(Y.t() @ Y)

tensor([[ 1.6179, -1.4446, -0.5412],
        [-1.4446,  3.0450, -0.2556],
        [-0.5412, -0.2556,  1.1083]])

## More tensor operations

Operations are also available as methods.

In [14]:
A = torch.eye(3)
A.add(1)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [15]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Any operation that mutates a tensor in-place has a `_` suffix.

In [16]:
A.add_(1)
A

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

## Indexing and broadcasting
It works as expected/like numpy:

In [17]:
A[0, 0]

tensor(2.)

In [18]:
A[0]

tensor([2., 1., 1.])

In [19]:
A[0:2]

tensor([[2., 1., 1.],
        [1., 2., 1.]])

In [20]:
A[:, 1:3]

tensor([[1., 1.],
        [2., 1.],
        [1., 2.]])

## Converting

In [21]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [22]:
# torch --> numpy
B = A.numpy()
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

Note: torch and numpy can share the same memory / zero-copy

In [23]:
A.add_(.5)
A

tensor([[1.5000, 0.5000, 0.5000],
        [0.5000, 1.5000, 0.5000],
        [0.5000, 0.5000, 1.5000]])

In [24]:
B

array([[1.5, 0.5, 0.5],
       [0.5, 1.5, 0.5],
       [0.5, 0.5, 1.5]], dtype=float32)

In [25]:
# numpy --> torch
torch.from_numpy(np.eye(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)

# But what about the GPU?
How do I use the GPU?

If you have a GPU make sure that the right pytorch is installed
(check https://pytorch.org/ for details).

In [26]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

If you have a GPU you should get something like: 
`device(type='cuda', index=0)`

You can move data to the GPU by doing `.to(device)`.

In [27]:
data = torch.eye(3)
data = data.to(device)
data

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Now the computation happens on the GPU.

In [28]:
res = data + data
res

tensor([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]])

In [29]:
res.device

device(type='cpu')